blank_issues_enabled: false
contact_links:
  - name: ğŸ“ è³ªå•ã‚„è­°è«–ã¯ã“ã¡ã‚‰ / Ask a question and discuss
    url: https://github.com/nishidayoshikatsu/github-templates-for-japanese/discussions
    about: ãƒ¡ãƒ³ãƒãƒ¼ã«è³ªå•ã‚„è­°è«–ã‚’ã™ã‚‹ / Ask questions and discuss with other community members
